kafka:
  producer:
    "bootstrap.servers": 'localhost:9092'
    "key.serializer": "org.apache.kafka.common.serialization.StringSerializer"
    "value.serializer": "ru.yandex.practicum.telemetry.kafka.EventSerializer"
  consumer:
    "bootstrap.servers": 'localhost:9092'
    "key.deserializer": "org.apache.kafka.common.serialization.StringDeserializer"
    "value.deserializer": "ru.yandex.practicum.telemetry.kafka.SensorEventDeserializer"
    "group.id": 'aggregator-1'
  topics:
    "sensor.event": '${SENSOR_EVENT_TOPIC:telemetry.sensors.v1}'
    "snapshot": '${SNAPSHOT_TOPIC:telemetry.snapshots.v1}'